<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ApplicationIcon />
    <AssemblyName>StellaUpscaling</AssemblyName>
    <RootNamespace>AnimeUpscaler</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AnimeUpscaler.Core\AnimeUpscaler.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>

